export type FieldType =
  | 'text'
  | 'password'
  | 'autocomplete'
  | 'number'
  | 'checkbox'
  | 'select'
  | 'datePicker'
  | 'textArea'
  | 'radio'
  | 'slideToggle'
  | 'slider'
  | 'timePicker'
  | 'chips'
  | 'dateRange'
  | 'color'
  | 'file';
